### ISSUE TITLE
Subharmonics: programming the PIC

### ISSUE THREAD

**Issue by RicardoVerschut** [m0xpd/SubHarmonics#1]
Hi Paul,

I've built the Subharmonics and found that I have no way to program the PIC as described. Are there any alternatives? I'd sure love to get this wonderful module to work.

Thanks in advance,
Ricardo

**Comment by m0xpd** [comment]
Hi Ricardo

Thanks for your interest in Subharmonics.
You need some kind of PIC-compatible programmer (like the pickit I used) to be able to complete this project.
I'll PM you on FaceBook.
Best-
Paul
